[package]
name = "front_schedule_leptos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common/" }

leptos = "0.4.5"
leptos_router = { version = "0.4.5", features = ["csr"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.103"
reqwasm = "0.5"
thiserror = "1.0.43"
serde-wasm-bindgen = "0.5.0"
gloo-net = "0.3.0"
